### ISSUE TITLE
How to automate prettier formatting before commit ?

### ISSUE THREAD

**Issue by flycatto** [resqiar/dikenang#56]
Sorry if this is a silly question, but i started looking for `CONTRIBUTING.md` and figured out this line;

> If you somehow disagree with these styleguide, you can do whatever style you think its best, but please run yarn format to format your code following our conventions before commit/creating any PR.

My question is, is there any way to automate this process? for me this is very annoying whenever i want to commit, i have to open new terminal and run prettier for formatting. Again, sorry if this is a silly question, but i want to know how to automate this process, maybe running some script? 

Thank you.

**Comment by resqiar** [comment]
Hi @flycatto, thank you for questioning this.
This problem can be solved with a tool called the pre-commit hook. the one that I am familiar with is Husky, they provide all the support for git hooks. If you want to know more about Husky and implement them with Prettier, I suggest you check [this documentation](https://prettier.io/docs/en/precommit.html). I plan to implement this, but if you want to fix this instead, send me PR.
